primary-solution = "main"
check-type = "builtin"
name = "a-plus-b"
title = "P == NP?" # Clickbait :)
random-seed = "09c5d2237e9b0e60"
valuer = "icpc"
valuer-cfg = "valuer.yaml"

[builtin-check]
name = "cmp-tokens"

[[tests]]
map = "1..2"
files = "%d.txt"
group = "samples"

[[tests]]
map = "3..5"
testgen = ["main"]
group = "tests"

[[tests]]
map = "6..7"
files = "%d.txt"
group = "tests"

[[tests]]
map = "8..20"
testgen = ["random"]
group = "tests"