title = "Calc sqrt"
name = "sqrt"
random-seed = "73ef6c014b4b2aa7"
check-type = "builtin"
primary-solution = "main"
valuer = "icpc"
valuer-cfg = "valuer.yaml"

[builtin-check]
name = "cmp-tokens"
cmd = ["--epsilon", "0.000001"]

[[tests]]
map = "1..3"
files = "%d.txt"
group = "samples"
